# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font: 75 italic 8pt \"Calibri\";\n"
"background-color: rgb(255, 255, 48);\n"
"color: rgb(76, 53, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.btn_nul = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nul.setGeometry(QtCore.QRect(0, 400, 100, 100))
        self.btn_nul.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_nul.setObjectName("btn_nul")
        self.btn_doriv_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_doriv_2.setGeometry(QtCore.QRect(100, 400, 100, 100))
        self.btn_doriv_2.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_doriv_2.setObjectName("btn_doriv_2")
        self.btn_ochust = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ochust.setGeometry(QtCore.QRect(200, 400, 100, 100))
        self.btn_ochust.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_ochust.setObjectName("btn_ochust")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(300, 400, 100, 100))
        self.btn_minus.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_one = QtWidgets.QPushButton(self.centralwidget)
        self.btn_one.setGeometry(QtCore.QRect(0, 300, 100, 100))
        self.btn_one.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_one.setObjectName("btn_one")
        self.btn_two = QtWidgets.QPushButton(self.centralwidget)
        self.btn_two.setGeometry(QtCore.QRect(100, 300, 100, 100))
        self.btn_two.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_two.setObjectName("btn_two")
        self.btn_three = QtWidgets.QPushButton(self.centralwidget)
        self.btn_three.setGeometry(QtCore.QRect(200, 300, 100, 100))
        self.btn_three.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_three.setObjectName("btn_three")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(300, 300, 100, 100))
        self.btn_plus.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_four = QtWidgets.QPushButton(self.centralwidget)
        self.btn_four.setGeometry(QtCore.QRect(0, 200, 100, 100))
        self.btn_four.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_four.setObjectName("btn_four")
        self.btn_five = QtWidgets.QPushButton(self.centralwidget)
        self.btn_five.setGeometry(QtCore.QRect(100, 200, 100, 100))
        self.btn_five.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_five.setObjectName("btn_five")
        self.btn_six = QtWidgets.QPushButton(self.centralwidget)
        self.btn_six.setGeometry(QtCore.QRect(200, 200, 100, 100))
        self.btn_six.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_six.setObjectName("btn_six")
        self.btn_dob = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dob.setGeometry(QtCore.QRect(300, 200, 100, 100))
        self.btn_dob.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_dob.setObjectName("btn_dob")
        self.btn_seven = QtWidgets.QPushButton(self.centralwidget)
        self.btn_seven.setGeometry(QtCore.QRect(0, 100, 100, 100))
        self.btn_seven.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_seven.setObjectName("btn_seven")
        self.btn_eight = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eight.setGeometry(QtCore.QRect(100, 100, 100, 100))
        self.btn_eight.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_eight.setObjectName("btn_eight")
        self.btn_nine = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nine.setGeometry(QtCore.QRect(200, 100, 100, 100))
        self.btn_nine.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_nine.setObjectName("btn_nine")
        self.btn_dellete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dellete.setGeometry(QtCore.QRect(300, 100, 100, 100))
        self.btn_dellete.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.btn_dellete.setObjectName("btn_dellete")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 100))
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setStyleSheet("border-radius:25px;\n"
"border:5px solid rgb(0, 0, 0);\n"
"font-size: 28px;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.btn_nul.setText(_translate("MainWindow", "0"))
        self.btn_doriv_2.setText(_translate("MainWindow", "="))
        self.btn_ochust.setText(_translate("MainWindow", "CE"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_one.setText(_translate("MainWindow", "1"))
        self.btn_two.setText(_translate("MainWindow", "2"))
        self.btn_three.setText(_translate("MainWindow", "3"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_four.setText(_translate("MainWindow", "4"))
        self.btn_five.setText(_translate("MainWindow", "5"))
        self.btn_six.setText(_translate("MainWindow", "6"))
        self.btn_dob.setText(_translate("MainWindow", "*"))
        self.btn_seven.setText(_translate("MainWindow", "7"))
        self.btn_eight.setText(_translate("MainWindow", "8"))
        self.btn_nine.setText(_translate("MainWindow", "9"))
        self.btn_dellete.setText(_translate("MainWindow", "/"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
