# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from img_rc import*


class Ui_Notes(object):
    def setupUi(self, Notes):
        Notes.setObjectName("Notes")
        Notes.resize(906, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Notes.setWindowIcon(icon)
        Notes.setStyleSheet("background-color: rgb(160, 160, 160);\n"
"\n"
"font: 75 italic 12pt \"Comic Sans MS\";")
        self.main_win = QtWidgets.QWidget(Notes)
        self.main_win.setObjectName("main_win")
        self.txt_edit = QtWidgets.QTextEdit(self.main_win)
        self.txt_edit.setGeometry(QtCore.QRect(26, 40, 442, 622))
        self.txt_edit.setStyleSheet("border-image: url(:/newPrefix/txt.PNG);")
        self.txt_edit.setObjectName("txt_edit")
        self.note_list1 = QtWidgets.QListWidget(self.main_win)
        self.note_list1.setGeometry(QtCore.QRect(520, 40, 342, 202))
        self.note_list1.setStyleSheet("border-image: url(:/newPrefix/list.PNG);")
        self.note_list1.setObjectName("note_list1")
        self.note_list2 = QtWidgets.QListWidget(self.main_win)
        self.note_list2.setGeometry(QtCore.QRect(520, 360, 342, 202))
        self.note_list2.setStyleSheet("border-image: url(:/newPrefix/list.PNG);")
        self.note_list2.setObjectName("note_list2")
        self.lbl = QtWidgets.QLabel(self.main_win)
        self.lbl.setGeometry(QtCore.QRect(520, 0, 342, 32))
        self.lbl.setObjectName("lbl")
        self.btn_add_note = QtWidgets.QPushButton(self.main_win)
        self.btn_add_note.setGeometry(QtCore.QRect(560, 260, 62, 62))
        self.btn_add_note.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-edit-3917361.png);")
        self.btn_add_note.setText("")
        self.btn_add_note.setObjectName("btn_add_note")
        self.btn_del_note = QtWidgets.QPushButton(self.main_win)
        self.btn_del_note.setGeometry(QtCore.QRect(760, 260, 62, 62))
        self.btn_del_note.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-trash-3917378.png);")
        self.btn_del_note.setText("")
        self.btn_del_note.setObjectName("btn_del_note")
        self.btn_save_note = QtWidgets.QPushButton(self.main_win)
        self.btn_save_note.setGeometry(QtCore.QRect(660, 260, 62, 62))
        self.btn_save_note.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-check-3917749.png);")
        self.btn_save_note.setText("")
        self.btn_save_note.setObjectName("btn_save_note")
        self.label = QtWidgets.QLabel(self.main_win)
        self.label.setGeometry(QtCore.QRect(540, 320, 342, 40))
        self.label.setObjectName("label")
        self.teg_find = QtWidgets.QLineEdit(self.main_win)
        self.teg_find.setGeometry(QtCore.QRect(520, 560, 342, 40))
        self.teg_find.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"")
        self.teg_find.setObjectName("teg_find")
        self.btn_add_teg = QtWidgets.QPushButton(self.main_win)
        self.btn_add_teg.setGeometry(QtCore.QRect(760, 620, 62, 62))
        self.btn_add_teg.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-user-add-3917698.png);")
        self.btn_add_teg.setText("")
        self.btn_add_teg.setObjectName("btn_add_teg")
        self.btn_final = QtWidgets.QPushButton(self.main_win)
        self.btn_final.setGeometry(QtCore.QRect(660, 620, 62, 62))
        self.btn_final.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-search-3917132.png);")
        self.btn_final.setText("")
        self.btn_final.setObjectName("btn_final")
        self.btn_del_teg = QtWidgets.QPushButton(self.main_win)
        self.btn_del_teg.setGeometry(QtCore.QRect(560, 620, 62, 62))
        self.btn_del_teg.setStyleSheet("border-image: url(:/newPrefix/free-icon-font-cross-3917759.png);")
        self.btn_del_teg.setText("")
        self.btn_del_teg.setObjectName("btn_del_teg")
        Notes.setCentralWidget(self.main_win)

        self.retranslateUi(Notes)
        QtCore.QMetaObject.connectSlotsByName(Notes)

    def retranslateUi(self, Notes):
        _translate = QtCore.QCoreApplication.translate
        Notes.setWindowTitle(_translate("Notes", "Notes edit"))
        self.lbl.setText(_translate("Notes", "Список заміток"))
        self.label.setText(_translate("Notes", "Список тегів"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Notes = QtWidgets.QMainWindow()
    ui = Ui_Notes()
    ui.setupUi(Notes)
    Notes.show()
    sys.exit(app.exec_())
